import * as t from '@babel/types';
export declare function buildRuntimeTypeCheckExpression(typeNode: t.TSType | null, valueId: t.Expression): t.Expression | null;
export declare function typeofCheck(valueId: t.Expression, type: string): t.Expression;
export declare function buildDateCheckExpression(valueId: t.Expression): t.Expression;
export declare function buildUrlCheckExpression(valueId: t.Expression): t.Expression;
export declare function buildArrayBufferCheckExpression(valueId: t.Expression): t.Expression;
export declare function buildLiteralTypeCheck(typeNode: t.TSLiteralType, valueId: t.Expression): t.Expression | null;
export declare function buildMapTypeCheckExpression(typeNode: t.TSTypeReference, valueId: t.Expression): t.Expression;
export declare function buildSetTypeCheckExpression(typeNode: t.TSTypeReference, valueId: t.Expression): t.Expression;
export declare function buildArrayTypeCheckExpression(typeNode: t.TSArrayType | t.TSTypeReference, valueId: t.Expression): t.Expression;
export declare function typeAllowsNull(typeNode: t.TSType | null): boolean;
export declare function buildNonNullObjectCheck(valueId: t.Expression): t.Expression;
export declare function buildTypeLiteralCheckExpression(typeLiteral: t.TSTypeLiteral, valueId: t.Expression): t.Expression;
export declare function buildMapTagComparison(valueExpr: t.Expression, tag: string): t.Expression;
export declare function buildSetTagComparison(valueExpr: t.Expression, tag: string): t.Expression;
export declare function buildObjectToStringCall(valueExpr: t.Expression): t.CallExpression;
