import * as t from '@babel/types';
import type { NodePath } from '@babel/traverse';
export declare function isDateReference(node: t.TSTypeReference): boolean;
export declare function isImmutableDateReference(node: t.TSTypeReference): boolean;
export declare function isUrlReference(node: t.TSTypeReference): boolean;
export declare function isImmutableUrlReference(node: t.TSTypeReference): boolean;
export declare function isArrayBufferReference(node: t.TSTypeReference): boolean;
export declare function isImmutableArrayBufferReference(node: t.TSTypeReference): boolean;
export declare function isSetReference(node: t.TSTypeReference): boolean;
export declare function isMapReference(node: t.TSTypeReference): boolean;
export declare function isBrandReference(node: t.TSTypeReference): boolean;
export declare function isPrimitiveKeyword(typePath: NodePath<t.TSType> | null | undefined): boolean;
export declare function isPrimitiveLiteral(typePath: NodePath<t.TSType> | null | undefined): boolean;
export declare function resolveQualifiedRoot(qualifiedName: t.TSQualifiedName): t.Identifier | null;
export declare function isArrayTypeNode(node: t.TSType | null | undefined): boolean;
export declare function isSetTypeNode(node: t.TSType | null | undefined): boolean;
export declare function isMapTypeNode(node: t.TSType | null | undefined): boolean;
export declare function getMapTypeArguments(node: t.TSType | null | undefined): {
    keyType: t.TSType;
    valueType: t.TSType;
} | null;
export declare function getSetTypeArguments(node: t.TSType | null | undefined): t.TSType | null;
export declare function getArrayElementType(node: t.TSType | null | undefined): t.TSType | null;
export declare function isPrimitiveLikeType(typePath: NodePath<t.TSType> | null | undefined): boolean;
export declare function getTypeName(typeNode: t.TSType): string | null;
